num_set = set([0, 1, 2, 3, 4, 5])
print("curren set elements:")
print(num_set)
print("Remove 0 from the current set:")
num_set.discard(0)
print(num_set)
print("Remove 5 from the current set:")
num_set.discard(5)
print(num_set)
print("Remove 2 from the current set:")
num_set.discard(5)
print(num_set)
print("Remove 7 from the current set:")
num_set.discard(15)
print(num_set)